pub const CODE_EXTENSIONS: [&str; 175] = [
    "rs",
    "py", "pyx", "pyi", "pyw",
    "js", "jsx", "ts", "tsx", "mjs", "cjs",
    "java", "kt", "kts", "scala", "groovy", "clj", "cljs",
    "c", "cc", "cpp", "cxx", "c++", "h", "hh", "hpp", "hxx", "h++",
    "cs", "csx",
    "go",
    "php", "php3", "php4", "php5", "phtml",
    "rb", "rbw", "rake", "gemspec",
    "swift",
    "m", "mm",
    "pl", "pm", "t", "pod",
    "sh", "bash", "zsh", "fish", "csh", "tcsh", "ksh",
    "ps1", "psm1", "psd1",
    "bat", "cmd",
    "r", "R", "rmd", "Rmd",
    "mlx",
    "lua",
    "dart",
    "hs", "lhs",
    "erl", "hrl", "ex", "exs",
    "fs", "fsx", "fsi",
    "vb", "vbs",
    "asm", "s", "S",
    "f", "f90", "f95", "f03", "f08",
    "cob", "cbl",
    "pas", "pp",
    "adb", "ads",
    "d",
    "nim", "nims",
    "cr",
    "zig",
    "jl",
    "ml", "mli",
    "re", "rei",
    "elm",
    "purs",
    "rkt",
    "scm", "ss",
    "lisp", "lsp", "l", "cl", "fasl",
    "sql", "psql", "mysql",
    "html", "htm", "xhtml", "xml", "xsl", "xslt",
    "css", "scss", "sass", "less", "styl",
    "vue", "svelte",
    "json", "jsonc", "yaml", "yml", "toml", "ini", "cfg", "conf",
    "env", "properties", "plist",
    "md", "markdown", "rst", "txt", "tex", "org", "adoc", "asciidoc",
    "hbs", "handlebars", "mustache", "twig", "jinja", "j2",
    "erb", "haml", "slim", "pug", "jade",
    "gradle", "sbt", "cmake", "make", "makefile", "dockerfile",
    "jenkinsfile", "vagrantfile", "gemfile", "podfile",
    "gitignore", "gitattributes",
    "proto", "graphql", "gql", "sol", "cairo", "move",
];